$(document).ready(function () {

    //Check
    console.log('Charts generated by Chart.JS');

    //Retrieving local data saved in Script.js from data.json
    var retrievedData = localStorage.getItem("gebruik");
    var dataCards = JSON.parse(retrievedData);
    console.log(dataCards);


    //Building the bar chart
    for (var i = 0; i < 6; i++) {


        // Factor to scale it to 6 on 6
        var factor = (dataCards[i] * 0.059);
        console.log('factor is: ' + factor);


        //Number of color|cards
        var number = i + 1;
        console.log(number);


        //Determining the flex number to alays fill out the the width
        var flexNumber = 6 - (6 / factor);
        console.log('.colorLine' + number + ' { flex: ' + flexNumber + ' }');
        $('.colorLine' + number).css('flex', ' ' + flexNumber);

    };




    //Building the Radar chart
    //Checking how much cards there are
    var amountOfCards = 0;
    countCards();

    function countCards() {
        $("canvas").each(function (index) {
            amountOfCards++;
            console.log(amountOfCards);

        });
    }


    //    //Dummy Data
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };


    for (var i = 0; i < amountOfCards; i++) {
        var color = Chart.helpers.color;
        var ctx = document.getElementById('canvas-' + i).getContext('2d');
        var myRadarChart = new Chart(ctx, {
            //Type of chart
            type: 'radar',

            //Type of dataSet
            data: {
                labels: [
                    ['Kennisverwerving'],
                    ['Productie'],
                    ['Praktijk'],
                    ['Samenwerking'],
                    ['Onderzoek'],
                    ['Discussie']


                ],
                datasets: [{
                    label: 'Mijn eerste reflectie',
                    backgroundColor: 'rgba(250, 218, 94, 0.2)' /**color(window.chartColors.yellow).alpha(0.2).rgbString()**/ ,
                    borderColor: 'rgba(250, 218, 94, 0.8)' /**window.chartColors.yellow**/ ,
                    pointBackgroundColor: 'rgba(50, 50, 50, 0.1)',
                    fontColor: 'rgb(210, 20, 71)',
                    data: [

                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                    ]
                }, {
                    label: 'Mijn eindresultaat',
                    backgroundColor: 'rgba(0,64, 255, 0.2)' /**color(window.chartColors.blue).alpha(0.2).rgbString()**/ ,
                    borderColor: 'rgba(0,64, 255, 0.8)' /**window.chartColors.blue**/ ,
                    pointBackgroundColor: 'rgba(51, 51, 51, 0.1)',
                    /* window.chartColors.blue */
                    data: [
                    // Retrieved from local data - see global var
                    dataCards[0],
                    dataCards[1],
                    dataCards[2],
                    dataCards[3],
                    dataCards[4],
                    dataCards[5]
                    ]
                }]
            },


            //Configuration of legend
            options: {
                legend: {
                    position: 'bottom',
                },
                title: {
                    text: 'Overzicht module'
                },
                scale: {
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        });

        //Not needed right now, but can be used for other functionalities
        //DO NOT DELETE

        //    window.onload = function () {
        //        window.myRadar = new Chart(document.getElementById('canvas'), config);
        //    };



        //var colorNames = Object.keys(window.chartColors);
        //        document.getElementById('addDataset').addEventListener('click', function() {
        //            var colorName = colorNames[config.data.datasets.length % colorNames.length];
        //            var newColor = window.chartColors[colorName];
        //
        //            var newDataset = {
        //                label: 'Dataset ' + config.data.datasets.length,
        //                borderColor: newColor,
        //                backgroundColor: color(newColor).alpha(0.2).rgbString(),
        //                pointBackgroundColor: newColor,
        //                data: [],
        //            };
        //
        //            for (var index = 0; index < config.data.labels.length; ++index) {
        //                newDataset.data.push(randomScalingFactor());
        //            }
        //
        //            config.data.datasets.push(newDataset);
        //            window.myRadar.update();
        //        });
    };

});
