$(document).ready(function () {

    //console.log('Charts generated by Chart.JS');

    //Retrieving local data saved in Script.js from data.json * NOT NEEDED FOR THE MOMENT
    //    var retrievedData = localStorage.getItem("gebruik");
    //    var dataCards = JSON.parse(retrievedData);

    var week = localStorage.getItem("weekBereik");
    //    console.log(week);
    var weekData = localStorage.getItem(week);
    //    console.log(weekData);


    //Global Variables to put in the chart
    var Kennisverwerving = countUsage(weekData, 'kennisverwerving');
    //    console.log(Kennisverwerving);

    var Productie = countUsage(weekData, 'productie');
    //    console.log(Productie);

    var Praktijk = countUsage(weekData, 'praktijk');
    //    console.log(Praktijk);

    var Samenwerking = countUsage(weekData, 'samenwerking');
    //    console.log(Samenwerking);

    var Onderzoek = countUsage(weekData, 'onderzoek');
    //    console.log(Onderzoek);

    var Discussie = countUsage(weekData, 'discussie');
    //    console.log(Discussie);

    //global array of the card usage values
    var dataCards = [Kennisverwerving, Productie, Praktijk, Samenwerking, Onderzoek, Discussie];


    /*  Found on w3resource:
    https://www.w3resource.com/javascript-exercises/javascript-string-exercise-18.php
    */
    function countUsage(main_str, sub_str) {
        main_str += '';
        sub_str += '';

        if (sub_str.length <= 0) {
            return main_str.length + 1;
        }

        subStr = sub_str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        return (main_str.match(new RegExp(subStr, 'gi')) || []).length;
    }


    //Building the bar chart
    for (var i = 0; i < 6; i++) {

        //Number of color|cards
        var number = i + 1;
        //Determining the flex number to alays fill out the the width
        var flexNumber = dataCards[i];
        //        console.log('.colorLine' + number + ' { flex: ' + flexNumber + ' }');
        $('.colorLine' + number).css('flex', ' ' + flexNumber);

        var value = $('.colorLine' + number).css('flex-grow') * 10;
        $('.colorLine' + number).children().html(number + ": " + value + '%');
    };

    //Toltip when hovering over  lineChart
    //    lineHover($(".colorLine1"));
    //    lineHover($(".colorLine2"));
    //    lineHover($(".colorLine3"));
    //    lineHover($(".colorLine4"));
    //    lineHover($(".colorLine5"));
    //    lineHover($(".colorLine6"));


    //    function lineHover(line) {
    //        $(line).hover(function () {
    //            var tipClass = $(this).attr("class").split(' ')[0];
    //            console.log(tipClass);
    //
    //            //Determining the value
    //            var value = $(line).css('flex-grow') * 10;
    //            console.log("The flex number of " + line + " is: " + value + "%");
    //
    //            //The tooltip
    //            var tooltipText = ('<span class="tooltipText">');
    //            $(tooltipText).html(value);
    //            $('.' + tipClass).append(tooltipText);
    //        });
    //
    //    };


    //Building the Radar chart
    //Checking how much cards there are
    var amountOfCards = 0;
    countCards();

    function countCards() {
        $("canvas").each(function (index) {
            amountOfCards++;
        });
    }


    //    //Dummy Data
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };
    // The chart itself
    for (var i = 0; i < amountOfCards; i++) {
        var color = Chart.helpers.color;
        var ctx = document.getElementById('canvas-' + i).getContext('2d');
        var myRadarChart = new Chart(ctx, {
            //Type of chart
            type: 'radar',

            //Type of dataSet
            data: {
                labels: [
                    ['Kennisverwerving'],
                    ['Productie'],
                    ['Praktijk'],
                    ['Samenwerking'],
                    ['Onderzoek'],
                    ['Discussie']


                ],
                datasets: [{
                    label: 'Mijn eerste reflectie',
                    backgroundColor: 'rgba(250, 218, 94, 0.2)' /**color(window.chartColors.yellow).alpha(0.2).rgbString()**/ ,
                    borderColor: 'rgba(250, 218, 94, 0.8)' /**window.chartColors.yellow**/ ,
                    pointBackgroundColor: 'rgba(50, 50, 50, 0.1)',
                    fontColor: 'rgb(210, 20, 71)',
                    data: [

                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                    ]
                }, {
                    label: 'Mijn eindresultaat',
                    backgroundColor: 'rgba(0,64, 255, 0.2)' /**color(window.chartColors.blue).alpha(0.2).rgbString()**/ ,
                    borderColor: 'rgba(0,64, 255, 0.8)' /**window.chartColors.blue**/ ,
                    pointBackgroundColor: 'rgba(51, 51, 51, 0.1)',
                    /* window.chartColors.blue */
                    data: [
                    // Retrieved from local data - see global var
                    dataCards[0],
                    dataCards[1],
                    dataCards[2],
                    dataCards[3],
                    dataCards[4],
                    dataCards[5]

                    ]
                }]
            },


            //Configuration of legend
            options: {
                legend: {
                    position: 'bottom',
                },
                title: {
                    text: 'Overzicht module'
                },
                scale: {
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        });

        //Not needed right now, but can be used for other functionalities
        //DO NOT DELETE

        //    window.onload = function () {
        //        window.myRadar = new Chart(document.getElementById('canvas'), config);
        //    };



        //var colorNames = Object.keys(window.chartColors);
        //        document.getElementById('addDataset').addEventListener('click', function() {
        //            var colorName = colorNames[config.data.datasets.length % colorNames.length];
        //            var newColor = window.chartColors[colorName];
        //
        //            var newDataset = {
        //                label: 'Dataset ' + config.data.datasets.length,
        //                borderColor: newColor,
        //                backgroundColor: color(newColor).alpha(0.2).rgbString(),
        //                pointBackgroundColor: newColor,
        //                data: [],
        //            };
        //
        //            for (var index = 0; index < config.data.labels.length; ++index) {
        //                newDataset.data.push(randomScalingFactor());
        //            }
        //
        //            config.data.datasets.push(newDataset);
        //            window.myRadar.update();
        //        });
    };

});
